namespace SampleProgram.UI
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose( bool disposing )
        {
            if ( disposing && ( components != null ) )
            {
                components.Dispose( );
            }
            base.Dispose( disposing );
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent( )
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager( typeof( MainForm ) );
            this.label1 = new System.Windows.Forms.Label( );
            this.label2 = new System.Windows.Forms.Label( );
            this.panel1 = new System.Windows.Forms.Panel( );
            this.fogbugzLogo = new System.Windows.Forms.PictureBox( );
            this.label3 = new System.Windows.Forms.Label( );
            this.label4 = new System.Windows.Forms.Label( );
            this.btnThrowException = new System.Windows.Forms.Button( );
            this.panel1.SuspendLayout( );
            ( (System.ComponentModel.ISupportInitialize) ( this.fogbugzLogo ) ).BeginInit( );
            this.SuspendLayout( );
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font( "Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ( (byte) ( 0 ) ) );
            this.label1.Location = new System.Drawing.Point( 169, 21 );
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size( 165, 19 );
            this.label1.TabIndex = 0;
            this.label1.Text = "Reporting Example";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font( "Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ( (byte) ( 0 ) ) );
            this.label2.ForeColor = System.Drawing.SystemColors.ControlDark;
            this.label2.Location = new System.Drawing.Point( 170, 43 );
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size( 217, 13 );
            this.label2.TabIndex = 1;
            this.label2.Text = "Using BugzScout to auto-report exceptions.";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add( this.fogbugzLogo );
            this.panel1.Controls.Add( this.label2 );
            this.panel1.Controls.Add( this.label1 );
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point( 0, 0 );
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size( 444, 76 );
            this.panel1.TabIndex = 2;
            // 
            // fogbugzLogo
            // 
            this.fogbugzLogo.Cursor = System.Windows.Forms.Cursors.Hand;
            this.fogbugzLogo.Image = global::SampleProgram.Properties.Resources.Fogbugz_kiwi;
            this.fogbugzLogo.Location = new System.Drawing.Point( 12, 12 );
            this.fogbugzLogo.Name = "fogbugzLogo";
            this.fogbugzLogo.Size = new System.Drawing.Size( 154, 50 );
            this.fogbugzLogo.TabIndex = 0;
            this.fogbugzLogo.TabStop = false;
            this.fogbugzLogo.Click += new System.EventHandler( this.fogbugzLogo_Click );
            // 
            // label3
            // 
            this.label3.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.label3.Location = new System.Drawing.Point( 0, 74 );
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size( 600, 2 );
            this.label3.TabIndex = 3;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point( 12, 89 );
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size( 312, 13 );
            this.label4.TabIndex = 4;
            this.label4.Text = "Any exceptions generated by this program are reported. Try it!";
            // 
            // btnThrowException
            // 
            this.btnThrowException.Location = new System.Drawing.Point( 15, 112 );
            this.btnThrowException.Name = "btnThrowException";
            this.btnThrowException.Size = new System.Drawing.Size( 111, 25 );
            this.btnThrowException.TabIndex = 5;
            this.btnThrowException.Text = "Throw Exception";
            this.btnThrowException.UseVisualStyleBackColor = true;
            this.btnThrowException.Click += new System.EventHandler( this.btnThrowException_Click );
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF( 6F, 13F );
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size( 444, 157 );
            this.Controls.Add( this.btnThrowException );
            this.Controls.Add( this.label4 );
            this.Controls.Add( this.label3 );
            this.Controls.Add( this.panel1 );
            this.Font = new System.Drawing.Font( "Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ( (byte) ( 0 ) ) );
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ( (System.Drawing.Icon) ( resources.GetObject( "$this.Icon" ) ) );
            this.MaximizeBox = false;
            this.Name = "MainForm";
            this.Text = "Sample App";
            this.panel1.ResumeLayout( false );
            this.panel1.PerformLayout( );
            ( (System.ComponentModel.ISupportInitialize) ( this.fogbugzLogo ) ).EndInit( );
            this.ResumeLayout( false );
            this.PerformLayout( );

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.PictureBox fogbugzLogo;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Button btnThrowException;
    }
}

